name: projeto_tcc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter

  dio: ^4.0.6
  get: ^4.6.3
  uuid: ^3.0.6
  crypt: ^4.2.1
  intl: ^0.17.0
  lottie: ^1.3.0
  pinput: ^2.2.9
  shimmer: ^2.0.0
  flip_card: ^0.6.0
  sqflite: ^2.0.2+1
  im_stepper: ^1.0.0
  flutter_svg: ^1.0.3
  reorderables: ^0.5.0
  bottom_sheet: ^3.1.1
  firebase_auth: ^3.5.0
  age_calculator: ^1.0.0
  firebase_core: ^1.20.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.4.0
  cupertino_icons: ^1.0.4
  email_validator: ^2.0.1
  qr_code_scanner: ^1.0.0
  responsive_sizer: ^3.0.8
  firebase_storage: ^10.3.3
  flutter_flavorizr: ^2.1.3
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.1.0
  rounded_loading_button: ^2.1.0
  credit_card_type_detector: ^2.0.0
  mask_text_input_formatter: ^2.3.0
  syncfusion_flutter_calendar: ^20.1.56

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.0
  flutter_launcher_icons: ^0.9.0

# Rodar sempre que quiser atualizar a splashscreen
# flutter clean
# flutter pub get
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  background_image: lib/app/assets/images/icons/background.png
  background_image_dark: lib/app/assets/images/icons/background.png
  image: lib/app/assets/images/icons/logo_pce.png
  image_dark: lib/app/assets/images/icons/logo_pce.png

  android_12:
    background_image: lib/app/assets/images/icons/background.png
    background_image_dark: lib/app/assets/images/icons/background.png
    image: lib/app/assets/images/icons/logo_pce.png
    image_dark: lib/app/assets/images/icons/logo_pce.png

  web: false

# Rodar sempre que quiser atualizar o icone
# flutter clean
# flutter pub get
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "lib/app/assets/images/icons/logo_pce_icone.png"
  adaptive_icon_background: "#603D7B"
  adaptive_icon_foreground: "lib/app/assets/images/icons/logo_pce_icone.png"

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    dev:
      app:
        name: "PCE DEV"
      android:
        applicationId: "com.prototipo_controle_educacional_dev"
      ios:
        bundleId: "com.prototipo_controle_educacional_dev"
    hmlg:
      app:
        name: "PCE HMLG"
      android:
        applicationId: "com.prototipo_controle_educacional_hmlg"
      ios:
        bundleId: "com.prototipo_controle_educacional_hmlg"
    prod:
      app:
        name: "PCE"
      android:
        applicationId: "com.prototipo_controle_educacional"
      ios:
        bundleId: "com.prototipo_controle_educacional"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/app/assets/images/
    - lib/app/assets/images/icons/
    - lib/app/assets/svgs/
    - lib/app/assets/json/